"""Research report generation.

Builds a research-oriented patient analysis report from a prediction plus its
explanation payload.  Sections follow the specification: overview, risk
assessment, temporal evidence, physiological evidence, text evidence, model
explanation, uncertainty, prediction horizon, limitations, disclaimer.

Exports: Markdown (default), JSON, CSV (structured results).  PDF is
explicitly listed as a limitation of the demo environment (see docs/limitations).
"""

from __future__ import annotations

import json
import logging
from pathlib import Path
from typing import Any, Optional

import pandas as pd

from synk.data.schemas import REFERENCE_RANGES_NOTE, VARIABLE_LABELS
from synk.evaluation.metrics import risk_category
from synk.utils.common import new_id, utcnow_iso

logger = logging.getLogger(__name__)

REPORT_DISCLAIMER = (
    "This report was generated by SYNK, a research prototype for studying early "
    "sepsis risk stratification. It is not for clinical diagnosis or treatment. "
    "All probabilities are model estimates with uncertainty; they are not "
    "certainties and not medical advice."
)

REPORT_LIMITATIONS = [
    "Model outputs are associations learned from data, not causal effects.",
    "Attributions indicate which inputs influenced the model, not which therapy is indicated.",
    "Calibration and thresholds are configurable study parameters, not clinically validated cut-offs.",
    "When run on synthetic data, every value in this report is synthetic demonstration data.",
]


def build_patient_report(
    patient_id: str,
    encounter_id: str,
    prediction_row: pd.Series,
    explanation: dict[str, Any],
    config,
    observations: Optional[pd.DataFrame] = None,
    notes: Optional[pd.DataFrame] = None,
) -> dict[str, Any]:
    """Assemble the report structure (JSON-serialisable dict)."""
    prob = float(prediction_row["risk_probability"])
    horizon = float(prediction_row.get("prediction_horizon_hours", config.labels.horizon_hours))
    unc = explanation.get("uncertainty", {})

    top_variables = []
    attr = explanation.get("structured_attribution", {})
    for item in attr.get("variables", [])[:5]:
        label = VARIABLE_LABELS.get(item["name"], item["name"])
        top_variables.append({"variable": item["name"], "label": label, "score": float(item["score"])})

    evidence_phrases = []
    for note_ev in explanation.get("text_evidence", []):
        for span in note_ev.get("evidence", {}).get("spans", []):
            if not span.get("negated"):
                evidence_phrases.append({
                    "text": span["text"],
                    "category": span["category"],
                })

    fusion = explanation.get("fusion_contribution")

    report: dict[str, Any] = {
        "report_id": new_id("rpt"),
        "generated_at": utcnow_iso(),
        "patient_id": patient_id,
        "encounter_id": encounter_id,
        "prediction_time": str(prediction_row.get("t", "")),
        "risk_assessment": {
            "risk_probability": prob,
            "risk_category": prediction_row.get("risk_category", risk_category(prob, config.evaluation.risk_thresholds)),
            "prediction_horizon_hours": horizon,
            "model_version": str(prediction_row.get("model_version", "unknown")),
            "engine": str(prediction_row.get("engine", "unknown")),
            "uncertainty": unc,
        },
        "physiological_evidence": {
            "top_variables": top_variables,
            "trend_summary": explanation.get("trend_summary", []),
        },
        "clinical_text_evidence": {
            "positive_categories": sorted({e["category"] for e in evidence_phrases}),
            "evidence_phrases": evidence_phrases[:20],
        },
        "model_explanation": {
            "attribution_method": attr.get("method"),
            "fusion_contribution": fusion,
            "note": "Attributions are model evidence for research interpretation, not clinical recommendations.",
        },
        "limitations": REPORT_LIMITATIONS,
        "disclaimer": REPORT_DISCLAIMER,
    }
    if observations is not None and len(observations):
        enc_obs = observations[observations["encounter_id"] == encounter_id].sort_values("timestamp")
        report["temporal_evidence"] = {
            "n_observations": int(len(enc_obs)),
            "first_observation": str(enc_obs["timestamp"].min()) if len(enc_obs) else None,
            "last_observation": str(enc_obs["timestamp"].max()) if len(enc_obs) else None,
        }
    if notes is not None and len(notes):
        enc_notes = notes[notes["encounter_id"] == encounter_id]
        report["clinical_notes_summary"] = {
            "n_notes": int(len(enc_notes)),
            "note_types": sorted(set(enc_notes.get("note_type", pd.Series(dtype=str)).astype(str))),
        }
    return report


def report_to_markdown(report: dict[str, Any]) -> str:
    """Render the report dict as readable Markdown."""
    ra = report["risk_assessment"]
    lines: list[str] = []
    lines.append(f"# SYNK Research Report - patient {report['patient_id']}")
    lines.append("")
    lines.append(f"*Encounter*: `{report['encounter_id']}`  ")
    lines.append(f"*Prediction time*: {report['prediction_time']}  ")
    lines.append(f"*Generated*: {report['generated_at']}")
    lines.append("")
    lines.append("> " + REPORT_DISCLAIMER)
    lines.append("")

    lines.append("## Risk assessment")
    lines.append("")
    lines.append(f"- **Risk probability**: {ra['risk_probability']:.3f} ({ra['risk_category']})")
    lines.append(f"- **Prediction horizon**: {ra['prediction_horizon_hours']:.0f} h")
    lines.append(f"- **Model**: {ra['engine']} (version {ra['model_version']})")
    unc = ra.get("uncertainty") or {}
    if unc.get("available"):
        lines.append(
            f"- **Uncertainty (MC dropout)**: std {unc.get('std_deviation', float('nan')):.3f}, "
            f"95% interval [{unc.get('ci95_low', float('nan')):.3f}, {unc.get('ci95_high', float('nan')):.3f}]"
        )
    else:
        note = unc.get("note", "No uncertainty estimate available for this engine.")
        lines.append(f"- **Uncertainty**: {note}")
    lines.append("")

    lines.append("## Physiological evidence (model attribution)")
    lines.append("")
    for item in report["physiological_evidence"]["top_variables"]:
        lines.append(f"- {item['label']} (`{item['variable']}`): attribution {item['score']:.4f}")
    lines.append("")
    lines.append(f"*{REFERENCE_RANGES_NOTE} Attribution scores are unitless model quantities.*")
    lines.append("")

    lines.append("## Temporal trends")
    lines.append("")
    for t in report["physiological_evidence"]["trend_summary"]:
        if t.get("status") == "ok":
            label = VARIABLE_LABELS.get(t["variable"], t["variable"])
            lines.append(
                f"- {label}: {t['direction']} (slope {t['slope_per_hour']:+.3f} sigma/h over "
                f"{t['n_observed']} observed hours)"
            )
    lines.append("")

    lines.append("## Clinical text evidence")
    lines.append("")
    ev = report["clinical_text_evidence"]
    if ev["evidence_phrases"]:
        lines.append("Non-negated evidence phrases detected in the notes window:")
        lines.append("")
        for e in ev["evidence_phrases"]:
            lines.append(f"- `{e['text']}` ({e['category']})")
    else:
        lines.append("No non-negated evidence phrases detected in the notes window.")
    lines.append("")

    lines.append("## Model explanation")
    lines.append("")
    me = report["model_explanation"]
    lines.append(f"- Attribution method: {me.get('attribution_method')}")
    fc = me.get("fusion_contribution")
    if fc:
        lines.append(
            f"- Fusion contribution: structured {fc['structured']:.0%} / text {fc['text']:.0%} "
            "(gated-fusion proxy, not causation)"
        )
    lines.append("")
    lines.append(f"> {me['note']}")
    lines.append("")

    lines.append("## Limitations")
    lines.append("")
    for lim in report["limitations"]:
        lines.append(f"- {lim}")
    lines.append("")
    return "\n".join(lines)


def save_report(
    report: dict[str, Any],
    directory: Path,
    formats: tuple[str, ...] = ("json", "md"),
) -> dict[str, str]:
    """Write the report in the requested formats; returns format -> path."""
    directory = Path(directory)
    directory.mkdir(parents=True, exist_ok=True)
    out: dict[str, str] = {}
    rid = report["report_id"]

    if "json" in formats:
        p = directory / f"{rid}.json"
        p.write_text(json.dumps(report, indent=2, default=str), encoding="utf-8")
        out["json"] = str(p)
    if "md" in formats:
        p = directory / f"{rid}.md"
        p.write_text(report_to_markdown(report), encoding="utf-8")
        out["md"] = str(p)
    if "csv" in formats:
        rows = []
        for item in report["physiological_evidence"]["top_variables"]:
            rows.append({
                "report_id": rid,
                "patient_id": report["patient_id"],
                "encounter_id": report["encounter_id"],
                "variable": item["variable"],
                "attribution": item["score"],
            })
        p = directory / f"{rid}_attributions.csv"
        pd.DataFrame(rows).to_csv(p, index=False)
        out["csv"] = str(p)
    logger.info("Report %s saved in formats: %s", rid, list(out))
    return out
